import { Inter } from 'next/font/google';
import './globals.css';
import GlobalState from '@/context';
import Sidebar from '@/components/Sidebar';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <GlobalState>
          <div className="flex h-screen ">
            {/* <Sidebar /> */}

            <div className="">
              <Header />
              <main>
                <div className="mx-auto max-w-screen-2xl">{children}</div>
              </main>
            </div>
          </div>
        </GlobalState>
      </body>
    </html>
  );
}
